In [1]:
import requests

In [2]:
url = "https://github.com/topics"

In [3]:
content = requests.get(url)

In [4]:
content

In [5]:
content.text[:300]                  #show starting first 300 words from content

'\n\n<!DOCTYPE html>\n<html\n  lang="en"\n  \n  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"\n  data-a11y-animated-images="system" data-a11y-link-underlines="true"\n  \n  >\n\n\n\n\n  <head>\n    <meta charset="utf-8">\n  <link rel="dns-prefetch" href="https://github.githubassets.com">\n  <l'

In [6]:
pip install BeautifulSoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: BeautifulSoup4 in c:\users\dell\appdata\roaming\python\python312\site-packages (4.13.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from BeautifulSoup4) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from BeautifulSoup4) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from bs4 import BeautifulSoup

In [8]:
soup = BeautifulSoup(content.text , "html.parser")

In [9]:
len(soup)

5

In [10]:
topics=[]
desc=[]
links=[]

In [11]:
for row in soup.find_all('a', class_='no-underline flex-1 d-flex flex-column'):
    topics.append(row.find('p').text.strip())
    desc.append(row.find_all('p')[1].text.strip())
    links.append('https://github.com' + row['href'])

In [12]:
import pandas as pd

In [15]:
df=pd.DataFrame({
    'Topic':topics,
    'Description':desc,
    'Link':links
    })

In [16]:
df

,Topic,Description,Link
0,Awesome Lists,An awesome list is a list of awesome things cu...,https://github.com/topics/awesome
1,Chrome,Chrome is a web browser from the tech company ...,https://github.com/topics/chrome
2,Code quality,"Automate your code review with style, quality,...",https://github.com/topics/code-quality
3,Compiler,Compilers are software that translate higher-l...,https://github.com/topics/compiler
4,CSS,Cascading Style Sheets (CSS) is a language use...,https://github.com/topics/css
5,Database,A database is a structured set of data held in...,https://github.com/topics/database
6,Front end,Front end is the programming and layout that p...,https://github.com/topics/frontend
7,JavaScript,JavaScript (JS) is a lightweight interpreted p...,https://github.com/topics/javascript
8,Node.js,Node.js is a tool for executing JavaScript in ...,https://github.com/topics/nodejs
9,npm,npm is a package manager for JavaScript includ...,https://github.com/topics/npm
10,Project management,Project management is about building scope and...,https://github.com/topics/project-management
11,Python,Python is a dynamically typed programming lang...,https://github.com/topics/python
12,React,React is an open source JavaScript library use...,https://github.com/topics/react
13,React Native,React Native is a JavaScript mobile framework ...,https://github.com/topics/react-native
14,Scala,Scala is an object-oriented programming language.,https://github.com/topics/scala
15,TypeScript,TypeScript is a typed superset of JavaScript t...,https://github.com/topics/typescript

In [28]:
users=[]
repo=[]
links=[]
stars=[]

In [25]:
for url in df['Link']:
    content=requests.get(url)
    soup=BeautifulSoup(content.text,'html.parser')
    for row in soup.find_all('div',class_='d-flex flex-justify-between flex-items-start flex-wrap gap-2 tmp-my-3'):
        users.append(row.find('a').text.strip())
        repo.append(row.find_all('a')[1].text.strip())
        stars.append(row.find('span' , id='repo-stars-counter-star')['title'].strip().replace(',',''))
        links.append('https://github.com'+row.find_all('a')[1]['href'])

In [29]:
print(len(users))
print(len(repo))
print(len(stars))
print(len(links))

0
0
0
0

In [30]:
df2 = pd.DataFrame({
    'Username': users,
    'Repository': repo,
    'Stars': stars,
    'Link': links
})

In [31]:
df2.shape

(0, 4)

In [39]:
df2.head(5)

Empty DataFrame
Columns: [Username, Repository, Stars, Link]
Index: []

In [35]:
df2.to_csv("github_best_topic_repo.csv")

In [40]:
df2.to_csv("github_best_topic_repo.csv", index=False)

In [41]:
df2

Empty DataFrame
Columns: [Username, Repository, Stars, Link]
Index: []